Revert "PCI: endpoint: pci-epf-test: Limit PCIe BAR size for fixed BARs"
This reverts commit 3289c66230645e476893f89c267d5037335f107f.

below build error is seen, to unblock the SRU the change is being reverted

/home/pshete/l4t-rel-39-20260330/out/l4t-generic-release-aarch64/nvidia/kernel-noble/kernel/src-soc/3rdparty/canonical/linux-noble/drivers/pci/endpoint/functions/pci-epf-test.c:863:33: error: 'const struct pci_epc_features' has no member named 'bar'
  863 |                 if (epc_features->bar[bar].type == BAR_FIXED)
      |                                 ^~
/home/pshete/l4t-rel-39-20260330/out/l4t-generic-release-aarch64/nvidia/kernel-noble/kernel/src-soc/3rdparty/canonical/linux-noble/drivers/pci/endpoint/functions/pci-epf-test.c:863:52: error: 'BAR_FIXED' undeclared (first use in this function)
  863 |                 if (epc_features->bar[bar].type == BAR_FIXED)
      |                                                    ^~~~~~~~~
/home/pshete/l4t-rel-39-20260330/out/l4t-generic-release-aarch64/nvidia/kernel-noble/kernel/src-soc/3rdparty/canonical/linux-noble/drivers/pci/endpoint/functions/pci-epf-test.c:863:52: note: each undeclared identifier is reported only once for each function it appears in
/home/pshete/l4t-rel-39-20260330/out/l4t-generic-release-aarch64/nvidia/kernel-noble/kernel/src-soc/3rdparty/canonical/linux-noble/drivers/pci/endpoint/functions/pci-epf-test.c:864:53: error: 'const struct pci_epc_features' has no member named 'bar'
  864 |                         test_reg_size = epc_features->bar[bar].fixed_size;
      |                                                     ^~

Bug 5796097

Change-Id: Ic4d028e99aeeb40fe5435ac84b6b7ebf8e3353a8
Signed-off-by: Prathamesh Shete <pshete@nvidia.com>