NVIDIA: SAUCE: tegra_hv: change to fix compilation error
BugLink: https://bugs.launchpad.net/bugs/2136282

change to fix below compilation error
kernel-nvidia-tests-oot/nvidia-tests-oot/drivers/tegra_hv_api_test/tegra_hv_test_api.o:
kernel-nvidia-tests-oot/linux-headers/./include/soc/tegra/virt/tegra_hv_sysmgr.h:110:
multiple definition of `vm_state'; kernel-nvidia-tests-oot/nvidia-tests-oot/drivers/
tegra_hv_api_test/tegra_hv_test.o:kernel-nvidia-tests-oot/linux-headers/./include/
soc/tegra/virt/tegra_hv_sysmgr.h:110: first defined here

http://nvbugs/5579375

Signed-off-by: Manish Bhardwaj <mbhardwaj@nvidia.com>
Reviewed-by: Suresh Venkatachalam <skathirampat@nvidia.com>
Reviewed-by: Sandeep Trasi <strasi@nvidia.com>
Signed-off-by: Prathamesh Shete <pshete@nvidia.com>
Acked-by: Jacob Martin <jacob.martin@canonical.com>
Acked-by: Noah Wager <noah.wager@canonical.com>
Signed-off-by: Noah Wager <noah.wager@canonical.com>